class Stock:...
class SavingAccount:...
class CheckingAccount:...
class RealEstate:...
class Bond:...
class BankAccount(SavingAccount, CheckingAccount):...
class Security(Stock, Bond):...
class Asset(BankAccount, Security, RealEstate):...
class InsurableItem(BankAccount, RealEstate):...
class InterestBearingItem(BankAccount, Security):...

# print(InterestBearingItem.mro(), '\n')
# print(Asset.mro(), '\n')
